package minecraft.wrapper;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;

/**
 * <b>Service: Geyser Configuration</b>
 * <p>
 * Manages the {@code plugins/Geyser-Spigot/config.yml} file.
 * Strictly adheres to "modification only" - never creates the file from scratch.
 * </p>
 */
public class GeyserConfig {

    private final File serverDir;

    /**
     * Constructs a new GeyserConfig manager.
     *
     * @param serverDir The server's root directory.
     */
    public GeyserConfig(File serverDir) {
        this.serverDir = serverDir;
    }

    /**
     * Configures Geyser with necessary overrides (MTU: 1200).
     * Assumes the config file exists (generated by Loader or previous run).
     *
     * @throws IOException If file operations fail.
     */
    public void configure() throws IOException {
        File pluginsDir = new File(serverDir, "plugins");
        File geyserDir = new File(pluginsDir, "Geyser-Spigot");
        File configFile = new File(geyserDir, "config.yml");
        
        if (configFile.exists()) {
            updateExistingConfig(configFile);
        } else {
            System.out.println("Config: Geyser config.yml not found. Skipping configuration (assuming fresh install waiting for first run).");
        }
    }

    /**
     * Updates an existing config file with the required MTU setting.
     *
     * @param file The configuration file to update.
     * @throws IOException If reading or writing fails.
     */
    private void updateExistingConfig(File file) throws IOException {
        String content = Files.readString(file.toPath(), StandardCharsets.UTF_8);
        String newContent = content;
        
        // Fix MTU for OCI/Cloud
        // Matches "mtu: [number]" and replaces with "mtu: 1200"
        if (newContent.contains("mtu:")) {
             newContent = newContent.replaceAll("mtu: \\d+", "mtu: 1200");
        } else {
             System.out.println("Config: Warning - 'mtu' key not found in existing Geyser config. Skipping update.");
        }
        
        if (!newContent.equals(content)) {
            Files.writeString(file.toPath(), newContent, StandardOpenOption.TRUNCATE_EXISTING);
            System.out.println("Config: Updated Geyser config.yml (MTU set to 1200).");
        }
    }
}